In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("tryout.csv")
# df.head()
df=df[['CRIM','ZN','INDUS','CHAS','NOX','AGE','DIS','RAD','PTRATIO','B','LSTAT','MEDV','TAX']]

df.columns[df.isnull().any()]

Index([], dtype='object')

In [8]:
x=df.drop('TAX',axis=1)
y=df['TAX']

In [9]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [12]:
# let k=69

from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=69)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=69)

In [15]:
y_test_hat=model.predict(x_test)

results=pd.DataFrame({'Actual':y_test,'Predictions':y_test_hat})
results.head(5)

Actual  Predictions
47      233          307
345     352          224
284     285          330
221     307          307
502     273          307

In [18]:
from sklearn.metrics import confusion_matrix,recall_score,precision_score

cm=confusion_matrix(y_test,y_test_hat)
print(cm)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_hat))

[[ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  4  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  2  0]]
              precision    recall  f1-score   support

         188       0.00      0.00      0.00         1
         193       0.00      0.00      0.00         2
         216       0.00      0.00      0.00         0
         222       0.00      0.00      0.00         5
         223       0.00      0.00      0.00         0
         224       0.22      0.50      0.31         4
         233       0.00      0.00      0.00         4
         245       0.00      0.00      0.00         3
         247       0.00      0.00      0.00         1
         252       0.00      0.00      0.00         1
         254       0.00      0.00      0.00         0
         264       0.50      0.25      0.33         4
         270       0.00      0.00      0.00         3
         273       0.00      0.00      0.00         2
         276       0.00      0.00

c:\Users\SUPRATIM NAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\SUPRATIM NAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\SUPRATIM NAG\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_pr